[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "blt"
version = "0.1.0"
description = "Book Listing Automation"
requires-python = ">=3.10"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["blt"]
